
// Objective-C API for talking to the following Go packages
//
//	thuanpham98/gif-go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GifResize_FRAMEWORK_H__
#define __GifResize_FRAMEWORK_H__

#include "Gif_resize.objc.h"
#include "Universe.objc.h"

#endif
